Repository CSC207-2023Y-UofT/ai-playground, pull requests merged in 2023-08, with the labels that each got.

#24 Building and training the Neural Net
  .github/CODEOWNERS
  .github/workflows/gradle-build.yml
  build.gradle
  src/main/java/com/playground/playground/modelling/ModelTrainingServices.java
  src/main/java/com/playground/playground/modelling/NeuralNet.java
  src/main/java/com/playground/playground/modelling/NeuralNetBuilder.java
  src/main/java/module-info.java
Labels: area/modelling, priority/high

#38 Documentation and tests for dataset generation
  src/main/java/com/playground/playground/GenerateDatasets.java
  src/main/java/com/playground/playground/Tests/TestGenerateDatasets.java
Labels: area/datasets, kind/documentation

#39 Sync fix-packages
  src/main/java/com/playground/playground/GenerateDatasets.java
  src/main/java/com/playground/playground/Tests/TestGenerateDatasets.java
Labels: kind/cleanup

#40 Create a new package called `data` to group datasets functionality
  src/main/java/com/playground/playground/Tests/TestGenerateDatasets.java
  src/main/java/com/playground/playground/data/FeatureController.java
  src/main/java/com/playground/playground/data/Features.java
  src/main/java/com/playground/playground/data/GenerateDatasets.java
  src/main/java/usecases/GenerateDatasets.java
Labels: priority/high, area/datasets, kind/cleanup

#42 User Interface
  .gitignore
  images/circle.png
  images/gauss.png
  images/spiral.png
  images/xor.png
  src/main/java/com/playground/playground/DataAttributesController.java
  src/main/java/com/playground/playground/FeaturesHiddenLayersController.java
  src/main/java/com/playground/playground/GraphSystemController.java
  src/main/java/com/playground/playground/MainApplication.java
  src/main/java/com/playground/playground/MainController.java
  src/main/java/com/playground/playground/MlParametersController.java
  src/main/resources/com/playground/playground/data-attributes-view.fxml
  src/main/resources/com/playground/playground/features-hidden-layers-view.fxml
  src/main/resources/com/playground/playground/graph-system-view.fxml
  src/main/resources/com/playground/playground/main-view.fxml
  src/main/resources/com/playground/playground/ml-parameters-view.fxml
Labels: hold, area/ui, priority/high

#43 Prepare model outputs for UI
  gradlew
  src/main/java/com/playground/playground/modelling/ModelTrainingServices.java
Labels: area/modelling, priority/mid

#49 Host Javadocs on GitHub Pages
  .github/workflows/publish-javadoc.yml
Labels: kind/documentation

#50 Fix NeuralNet documentation
  src/main/java/com/playground/playground/modelling/ModelTrainingServices.java
  src/main/java/com/playground/playground/modelling/NeuralNet.java
  src/main/java/com/playground/playground/modelling/NeuralNetBuilder.java
Labels: kind/documentation

#51 Dataset Generation Module with Design Patterns
  src/main/java/com/playground/playground/Tests/TestData.java
  src/main/java/com/playground/playground/Tests/TestGenerateDatasets.java
  src/main/java/com/playground/playground/Tests/TransformDatasetsTest.java
  src/main/java/com/playground/playground/data/CircularDatasetGenerator.java
  src/main/java/com/playground/playground/data/ClusterDatasetGenerator.java
  src/main/java/com/playground/playground/data/DataGeneratorFactory.java
  src/main/java/com/playground/playground/data/DataProcessor.java
  src/main/java/com/playground/playground/data/DatasetGenerator.java
  src/main/java/com/playground/playground/data/FeatureController.java
  src/main/java/com/playground/playground/data/GenerateDatasets.java
  src/main/java/com/playground/playground/data/QuadrantDatasetGenerator.java
  src/main/java/com/playground/playground/data/SpiralDatasetGenerator.java
  src/main/java/com/playground/playground/data/TransformDatasets.java
Labels: area/datasets

#66 Add documentation and tests for `PrepareData`
  src/main/java/com/playground/playground/modelling/PrepareData.java
  src/test/java/com/playground/playground/modelling/PrepareDataTest.java
Labels: area/datasets, kind/cleanup

#67 Updated data types to `INDArray`
  src/main/java/com/playground/playground/data/FeatureController.java
  src/test/java/com/playground/playground/data/DataTest.java
  src/test/java/com/playground/playground/data/FeatureTest.java
Labels: area/datasets, kind/cleanup

#73 Update docs for Controllers
  .github/workflows/lint.yml
  src/main/java/com/playground/playground/DataAttributesController.java
  src/main/java/com/playground/playground/FeaturesHiddenLayersController.java
  src/main/java/com/playground/playground/MainController.java
  src/main/java/com/playground/playground/MainLauncher.java
  src/main/java/com/playground/playground/MlParametersController.java
  src/main/java/com/playground/playground/data/FeatureApplier.java
  src/main/java/com/playground/playground/data/FeatureApplierFactory.java
  src/main/java/com/playground/playground/data/FeatureController.java
  src/main/java/com/playground/playground/data/MultiplyFeatureApplier.java
  src/main/java/com/playground/playground/data/SinFeatureApplier.java
  src/main/java/com/playground/playground/data/SquareFeatureApplier.java
  src/main/java/com/playground/playground/modelling/ModelTrainingServices.java
Labels: kind/documentation

#76 Add a link to the documentation in the README
  README.md
Labels: kind/documentation

#82 Remove Unused JavaFX elements for discretize, regenerate, test data, and step button
  src/main/java/com/playground/playground/interface_adapter/controller/DataAttributesController.java
  src/main/java/com/playground/playground/interface_adapter/controller/FeatureController.java
  src/main/java/com/playground/playground/interface_adapter/controller/FeaturesHiddenLayersController.java
  src/main/java/com/playground/playground/interface_adapter/controller/GraphSystemController.java
  src/main/java/com/playground/playground/interface_adapter/controller/MainController.java
  src/main/java/com/playground/playground/interface_adapter/controller/MlParametersController.java
  src/main/java/com/playground/playground/interface_adapter/modelling/ModelTrainingServices.java
  src/main/resources/com/playground/playground/data-attributes-view.fxml
  src/main/resources/com/playground/playground/features-hidden-layers-view.fxml
  src/main/resources/com/playground/playground/graph-system-view.fxml
  src/main/resources/com/playground/playground/main-view.fxml
  src/main/resources/com/playground/playground/ml-parameters-view.fxml
  src/main/resources/com/playground/playground/playground-images/stop-button.png
  src/test/java/com/playground/playground/data/FeatureTest.java
  src/test/java/com/playground/playground/modelling/ModelTrainingServicesTest.java
Labels: user interface, kind/cleanup

#84 Add tests for dataset generator classes
  src/test/java/com/playground/playground/data/DataTest.java
Labels: area/datasets

#85 Create Test Coverage badges
  .github/workflows/gradle-build.yml
Labels: kind/documentation

#89 Add test coverage badge to README
  README.md
Labels: kind/documentation

#95 Create Controller Tests
  src/main/java/com/playground/playground/controller/DataAttributesController.java
  src/main/java/com/playground/playground/controller/FeatureController.java
  src/main/java/com/playground/playground/controller/FeaturesHiddenLayersController.java
  src/main/java/com/playground/playground/controller/GraphSystemController.java
  src/main/java/com/playground/playground/controller/MlParametersController.java
  src/main/java/com/playground/playground/interface_adapter/views/DataAttributesView.java
  src/main/java/com/playground/playground/interface_adapter/views/FeaturesHiddenLayersView.java
  src/main/java/com/playground/playground/interface_adapter/views/GraphSystemView.java
  src/main/java/com/playground/playground/interface_adapter/views/MainView.java
  src/main/java/com/playground/playground/interface_adapter/views/MlParametersView.java
  src/test/java/com/playground/playground/controller/DataAttributesControllerTest.java
  src/test/java/com/playground/playground/controller/MlParametersControllerTest.java
  src/test/java/com/playground/playground/data/FeatureTest.java
Labels: testing

#93 Feature testing
  src/test/java/com/playground/playground/data/FeatureTest.java
  src/test/java/com/playground/playground/feature/FeatureApplierFactoryTest.java
  src/test/java/com/playground/playground/feature/FeatureControllerTest.java
  src/test/java/com/playground/playground/feature/MultiplyFeatureTest.java
  src/test/java/com/playground/playground/feature/SinFeatureTest.java
  src/test/java/com/playground/playground/feature/SquareFeatureTest.java
Labels: testing

#99 Add controllers to interface adapaters
  src/main/java/com/playground/playground/entity/DatasetType.java
  src/main/java/com/playground/playground/interface_adapter/controller/DataAttributesController.java
  src/main/java/com/playground/playground/interface_adapter/controller/FeatureController.java
  src/main/java/com/playground/playground/interface_adapter/controller/FeaturesHiddenLayersController.java
  src/main/java/com/playground/playground/interface_adapter/controller/GraphSystemController.java
  src/main/java/com/playground/playground/interface_adapter/controller/MlParametersController.java
  src/main/java/com/playground/playground/interface_adapter/modelling/ModelTrainingServices.java
  src/main/java/com/playground/playground/interface_adapter/views/DataAttributesView.java
  src/main/java/com/playground/playground/interface_adapter/views/FeaturesHiddenLayersView.java
  src/main/java/com/playground/playground/interface_adapter/views/GraphSystemView.java
  src/main/java/com/playground/playground/interface_adapter/views/MlParametersView.java
  src/main/java/com/playground/playground/usecase/datasets/CircularDatasetGenerator.java
  src/main/java/com/playground/playground/usecase/datasets/ClusterDatasetGenerator.java
  src/main/java/com/playground/playground/usecase/datasets/DataProcessor.java
  src/main/java/com/playground/playground/usecase/datasets/QuadrantDatasetGenerator.java
  src/main/java/com/playground/playground/usecase/datasets/SpiralDatasetGenerator.java
  src/main/java/com/playground/playground/usecase/features/MultiplyFeatureApplier.java
  src/main/java/com/playground/playground/usecase/features/SinFeatureApplier.java
  src/main/java/com/playground/playground/usecase/features/SquareFeatureApplier.java
  src/main/java/com/playground/playground/usecase/modelling/PrepareData.java
  src/test/java/com/playground/playground/entity/NeuralNetTest.java
  src/test/java/com/playground/playground/interface_adapter/controller/DataAttributesControllerTest.java
  src/test/java/com/playground/playground/interface_adapter/controller/FeatureControllerTest.java
  src/test/java/com/playground/playground/interface_adapter/controller/MlParametersControllerTest.java
  src/test/java/com/playground/playground/interface_adapter/modelling/ModelTrainingServicesTest.java
  src/test/java/com/playground/playground/usecase/datasets/CircularDatasetGeneratorTest.java
  src/test/java/com/playground/playground/usecase/datasets/ClusterDatasetGeneratorTest.java
  src/test/java/com/playground/playground/usecase/datasets/DataGeneratorFactoryTest.java
  src/test/java/com/playground/playground/usecase/datasets/DataProcessorTest.java
  src/test/java/com/playground/playground/usecase/datasets/QuadrantDatasetGeneratorTest.java
  src/test/java/com/playground/playground/usecase/datasets/SpiralDatasetGeneratorTest.java
  src/test/java/com/playground/playground/usecase/datasets/TransformDatasetsTest.java
  src/test/java/com/playground/playground/usecase/feature/FeatureApplierFactoryTest.java
  src/test/java/com/playground/playground/usecase/feature/MultiplyFeatureTest.java
  src/test/java/com/playground/playground/usecase/feature/SinFeatureTest.java
  src/test/java/com/playground/playground/usecase/feature/SquareFeatureTest.java
  src/test/java/com/playground/playground/usecase/modelling/PrepareDataTest.java
Labels: kind/cleanup
